/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'DMS',systemName:'企业文档管理系统',englishName:'DOCUMENT MANAGEMENT SYSTEM',theme:{primary:'#355f82',dark:'#1f2c38',accent:'#b6813f'},workspace:'集团知识中心 / 文控运营',fieldWorkspace:'研发技术文档库',period:'2026-08-01 · 周六',liveText:'归档与备份服务正常',fieldContextLabel:'当前文档库',fieldContext:'协作空间 · 受控访问',fieldUser:'许文博',fieldRole:'文档协作者',adminUser:'周妍',adminRole:'文控主管',
 adminTitle:'文档治理中心',adminBreadcrumb:'知识治理 / 文档态势',adminSubtitle:'掌握受控文件、审批、版本、分发与到期评审。',exportAction:'导出文控清单',createAction:'新建受控文档',chartTitle:'受控文档发布趋势',chartSubtitle:'本月累计发布 / 目标基线',chartLabels:['第1周','第2周','第3周','第4周','05日','10日','15日','20日','今日'],loadTitle:'文档库容量',loadSubtitle:'有效文件占治理计划',recordsTitle:'待办文档',recordsSubtitle:'按审批期限与影响范围排序',issueTitle:'治理风险',issueSubtitle:'版本、权限和归档异常',
 recordName:'受控文档',itemName:'文件名称',unitName:'文档库',batchName:'当前版本',planName:'总页数',doneName:'已核准',exceptionName:'待修订',unitLabel:'页',listBreadcrumb:'文档控制 / 受控文件',listSubtitle:'统一管理起草、会签、批准、发布、变更与作废。',listSummary:[['受控文件','1,286'],['本月发布','74'],['待审批','19'],['到期评审','6',true]],tabs:['全部','待发布','审批中','已发布','已作废'],
 fieldBreadcrumb:'文档协作 / 我的工作台',fieldTitle:'文档协作工作台',fieldSubtitle:'当前 5 项待办 · 3 个协作评审 · 文档工程师许文博',fieldSecondary:'查阅记录',reportAction:'提交新版本',fieldNoticeTitle:'权限与水印策略生效',fieldNotice:'下载、打印、外发和离线查阅均已纳入审计',steps:['内容起草','格式校验','协同会签','批准发布','受控分发'],documentAction:'在线预览',printAction:'下载受控副本',resourceCardTitle:'存储与归档',resourceValueLabel:'今日写入',resourceHealthLabel:'存储健康度',quickSubtitle:'协作与文控高频入口',quickActions:[['提交版本','/shopfloor/report','修订说明与附件'],['协同评审','/shopfloor/tasks','意见与会签'],['受控查阅','/shopfloor/material','权限与水印'],['权限申请','/shopfloor/andon','临时授权 / 外发']],
 reportDefaults:[12,1],reportTitle:'提交文档新版本',reportSubtitle:'登记修订页数、遗留问题和版本说明。',reportSuccess:'新版本已提交并进入协同评审',reportPlaceholder:'概述修订范围、原因和影响章节',reportFootnote:'系统将保留旧版并生成版本差异与审计记录',ruleTitle:'发布控制要求',ruleSubtitle:'SOP-QA-017 · V3.2',rules:[['模板规范','QMS-DOC-04'],['审批路径','部门 + 质量会签'],['电子签名','必须'],['旧版回收','自动执行',true]],fieldTotals:[['12','本周提交'],['3','待会签'],['18','协作意见'],['100%','审计覆盖率']],
 adminMenus:[['/admin','home','治理中心'],['/admin/work-orders','order','受控文件'],['/admin/libraries','box','文档库'],['/admin/schedule','calendar','到期评审'],['/admin/templates','process','模板规范'],['/admin/reviews','quality','审批中心'],['/admin/resources','machine','存储归档'],['/admin/report','chart','文控分析']],fieldMenus:[['/shopfloor','home','协作工作台'],['/shopfloor/report','report','版本提交'],['/shopfloor/tasks','order','我的待办'],['/shopfloor/material','box','受控查阅'],['/shopfloor/resources','machine','最近文件'],['/shopfloor/andon','risk','权限申请',2]],moduleTitles:{tasks:['我的待办','处理起草、评审、会签和发布任务'],material:['受控查阅','在授权范围内预览、下载和打印'],resources:['最近文件','查看收藏、最近访问与团队更新'],andon:['权限申请','申请临时查阅、外发或打印权限'],libraries:['文档库','管理分类、密级、保管期限和责任部门'],schedule:['到期评审','跟踪文件有效期与定期复审计划'],templates:['模板规范','维护文件模板、编号规则与格式标准'],reviews:['审批中心','执行会签、批准、退回和电子签名'],report:['文控分析','分析审批周期、更新频率和使用情况']},
 tagline:'让企业知识始终处于正确版本',storyTitle:'从起草到归档，<br/>每次修改都留下可靠依据。',storyText:'以版本、权限、流程和审计串联企业受控知识。',pattern:[1,2,3,7,8,9,14,15,16,21,22,27,28,29,34],loginStats:[['1,286','受控文件'],['100%','审计覆盖'],['2.4d','平均审批周期']],loginTitle:'企业知识中心',adminDemo:'文件 / 审批 / 权限',fieldDemo:'协作 / 版本 / 查阅'
}
export const records=[{no:'DOC-QA-2608-018',name:'来料检验作业指导书',code:'SOP-QA-017',unit:'质量体系文件库',group:'质量管理部',plan:42,done:36,exception:1,due:'08-02',batch:'V3.2',status:'审批中',progress:86,priority:'加急'},{no:'DOC-RD-2608-021',name:'AX120 产品技术规范',code:'SPEC-AX120',unit:'研发技术文档库',group:'研发中心',plan:68,done:52,exception:2,due:'08-03',batch:'V2.6',status:'审批中',progress:76,priority:'正常'},{no:'DOC-LEG-2608-006',name:'供应商保密协议模板',code:'TPL-NDA-04',unit:'合同与法务档案库',group:'法务部',plan:18,done:0,exception:0,due:'08-05',batch:'V1.4',status:'待发布',progress:0,priority:'正常'},{no:'DOC-QA-2607-015',name:'质量管理手册',code:'MAN-QMS-001',unit:'质量体系文件库',group:'质量管理部',plan:96,done:96,exception:1,due:'08-01',batch:'V5.0',status:'已发布',progress:100,priority:'正常'},{no:'DOC-RD-2608-024',name:'控制器接口设计说明',code:'DES-MC08',unit:'研发技术文档库',group:'研发中心',plan:54,done:34,exception:3,due:'08-04',batch:'V1.8',status:'审批中',progress:63,priority:'关注'}]
export const resources=[{code:'NODE-SH-01',name:'上海主存储节点',unit:'质量体系文件库',status:'运行',health:94,value:'38.6',valueUnit:'GB',note:'不可变备份已完成'},{code:'NODE-RD-02',name:'研发加密存储节点',unit:'研发技术文档库',status:'运行',health:91,value:'24.2',valueUnit:'GB',note:'密钥轮换正常'},{code:'NODE-DR-01',name:'异地灾备节点',unit:'灾备中心',status:'异常',health:67,value:'91',valueUnit:'ms',note:'复制延迟偏高'}]
export const reviews=[{no:'APR-260801-032',title:'来料检验指导书部门会签',type:'部门会签',detail:'4 位审批人 · 周妍',result:'通过'},{no:'APR-260801-011',title:'AX120 技术规范接口复核',type:'技术复核',detail:'3 条待修改意见',result:'待确认'},{no:'APR-260731-018',title:'质量手册发布审批',type:'发布批准',detail:'电子签名完整',result:'已完成'}]
export const adminMetrics=[['受控文件','1,286','有效文件 1,214 份','blue'],['按期复审率','97.4%','目标值 ≥ 96%','green'],['待审批','19','其中 4 项加急','orange'],['版本风险','6','旧版回收待确认','red']],fieldMetrics=[['我的待办','5','起草 2 · 会签 3','blue'],['本周提交','12','已发布 8 份','green'],['协作意见','18','待回复 4 条','orange'],['最近访问','46','过去 7 天','slate']]
export const chartActual=[9,17,28,39,46,58,69,82,93],chartTarget=[10,20,30,40,50,60,70,80,95],loads=[['质量体系文件库',92,'386 份受控文件'],['研发技术文档库',78,'524 份技术文档'],['合同与法务档案库',66,'218 份有效合同'],['人力资源档案库',54,'158 份制度文件']]
export const issues=[{type:'版本',title:'车间仍有 3 份 V3.1 纸质副本',detail:'SOP-QA-017 · 待回收确认',status:'跟进中'},{type:'权限',title:'外部协作链接将在 2 小时后到期',detail:'SPEC-AX120 · 访问 6 次',status:'待处理'},{type:'归档',title:'异地节点复制延迟超过阈值',detail:'NODE-DR-01 · 延迟 91ms',status:'处理中'}]
